### ISSUE TITLE
Provide a list of valid Api Keys and Basic Authentication logins via appsettings.json

### ISSUE THREAD

**Issue by marcominerva** [marcominerva/SimpleAuthentication#60]
Currently, **SimpleAuthentication** allows to specify only a single Api Key value and/or a single login/password (for Basic Authentication) using **appsettings.json**. If we want to support multiple fixed values, we need to create a custom handler in code.

I'm thinking if it worth the case to add support for multiple fixed values directly in the **appsettings.json**, for example in this way:

```
"Authentication": {
    "ApiKey": {
        "ApiKeys": [
            {
                "Value": "key-1",
                "UserName": "UserName1"
            },
            {
                "Value": "key-2",
                "UserName": "UserName2"
            }
        ]
    },
    "Basic": {
        "Credentials": [
            {
                "UserName": "UserName1",
                "Password": "Password1"
            },
            {
                "UserName": "UserName2",
                "Password": "Password2"
            }
        ]
    }
}
```

Of course, the old way to define values and credentials will continue to work. And, in the same way, the current way to customize authentication using the corresponding handlers will be still valid.

**Comment by alemik** [comment]
Great suggestion!

**Comment by Galvy** [comment]
Very interesting feature!
