### ISSUE TITLE
HttpContext.User is not populated

### ISSUE THREAD

**Issue by reza1mohammad** [marcominerva/SimpleAuthentication#99]
I tried to set HttpContext.User in the login method like this;

` if (loginRequest.Scopes?.Any() ?? false)
 {
     claims.Add(new("scp", loginRequest.Scopes));

     var identity = new ClaimsIdentity(claims, "CustomLogin");
     HttpContext.User = new ClaimsPrincipal(identity);
 }`

but after checking it in `MeController` there is no value in it. `IsAuthenticated = false`
How could I fix this problem?
I'm struggling with it for several days. 

thanks in advance

**Comment by reza1mohammad** [comment]
thanks for your response. I found nothing. Could you help me with that?

**Comment by marcominerva** [comment]
Take a look here: https://github.com/marcominerva/SimpleAuthentication/blob/f3205a960fecfe286d3eb1c24cb35331c049bf77/samples/Controllers/JwtBearerSample/Controllers/AuthController.cs#L18. Try the method with Swagger, then insert the Accesa Token in the Authenticate window of Swagger. Finally, invoke the MeController and you'll see you are authenticated

**Comment by reza1mohammad** [comment]
So, you mean to test the default code. I did it and `User` in the `MeController` was empty. I mean `IsAuthenticated = false`.
I added the `User` in MeController like this:

`public ActionResult<User> Get()
{
    var u = HttpContext.User;   //IsAuthenticated = false
    return new User(User.Identity!.Name);
}`

After that I tried to change the login method as I've shown in the previous message. but after all I got the same result.

**Comment by marcominerva** [comment]
The `Get` method in `MeController` has the `Authorize` attribute, so if you try to invoke it without the Authentication Token, you'll get a 401 response. I think you are missing something.

If you can create a sample repro with your code and share the link, I'll take a look to it.

**Comment by reza1mohammad** [comment]
could i share it using Google meet. https://meet.google.com/jaa-nctp-evo

**Comment by marcominerva** [comment]
Sorry, I can't join the call right now. You can add the project in the comment.

**Comment by reza1mohammad** [comment]
To be honest I just cloned you project, add the following code after `app.UseHttpsRedirection();` in the Program.cs and ran the project:

`app.UseAuthenticationAndAuthorization();`

**Comment by reza1mohammad** [comment]
> so if you try to invoke it without the Authentication Token, you'll get a 401 response. I think you are missing something.

Actually, I get 401 when calling MeController. due to `[Authorize]`. I just commented some of attributes to invoke to method.
I tried with swagger and postman and add the token to the Authorization header but I get 401.

**Comment by marcominerva** [comment]
Take a look to the video in the README.md, you'll see how to correctly use the library.

**Comment by reza1mohammad** [comment]
I found out what was the problem. the swagger version that I'm using add `Bearer` by default when authorizing. when I added a `Bearer` it became two `Bearer`. 🤣
